### ISSUE TITLE
Repository docs out of date?

### ISSUE THREAD

**Issue by themoritz** [1Jajen1/kotlin-pretty#8]
In which repository can this library be found currently? I tried 

```
maven("https://dl.bintray.com/jannis/kotlin-pretty")
```

(`Could not GET 'https://dl.bintray.com/jannis/kotlin-pretty/kotlin-pretty/kotlin-pretty/0.6.0/kotlin-pretty-0.6.0.pom'. Received status code 403 from server: Forbidden`)

and

```
maven("https://jitpack.io")
```

but both do not work.

**Comment by 1Jajen1** [comment]
Yeah bintray most likely shouldn't work anymore, a workaround should be [jitpack: https://jitpack.io/com/github/1Jajen1/kotlin-pretty/](https://jitpack.io/#1Jajen1/kotlin-pretty/0.6.0)

I "should" move this to some other maven repository for hosting, but I have been swamped by uni and life in general for quite a while and thats most likely not going to change any time soon.

For the 0.6 release this should work:
```
maven { url 'https://jitpack.io' }
```
and 
```
dependencies {
    api "com.github.1Jajen1.kotlin-pretty:kotlin-pretty:0.6.0"
}
```

See https://jitpack.io/#1Jajen1/kotlin-pretty/0.6.0 for more information, the UI there generates the dependency stuff for you, for any branch/tag/commit you want.

I know this is annoying, but I don't really have the time (or the knowledge, which again means time) to fix it right now :/

**Comment by themoritz** [comment]
TIL about what Jitpack is actually for. :) Works now, thanks a lot!
